[package]
name    = "universal-weave-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
universal-weave = { git = "https://github.com/transkatgirl/universal-weave.git", rev = "2cde2ea0357d52e1f6fbd308fdd382c147a24c47", features = [
	"layout",
	"rkyv",
	"serde",
	"loro",
] }
eframe = "0.35"
rfd = "0.17"
rkyv = { version = "0.8.17", features = [
	"bytecheck",
] }
