[package]
name    = "universal-weave-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
universal-weave = { version = "0.4.1", features = [
	"rkyv",
	"serde",
	"loro",
] }
universal-weave-ui = { git = "https://github.com/transkatgirl/universal-weave-ui.git" }
eframe = "0.35"
rfd = "0.17"
rkyv = { version = "0.8.17", features = [
	"bytecheck",
] }
