[package]
name    = "universal-weave-ratatui-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
ratatui = { version = "0.30.2", default-features = false, features = [
	"crossterm_0_29",
] }
rfd = "0.17"
universal-weave = { git = "https://github.com/transkatgirl/universal-weave.git", features = [
	"layout",
	"rkyv",
	"serde",
] }
rkyv = { version = "0.8.17", features = [
	"bytecheck",
] }
unicode-width = "0.2"

[patch.crates-io]
universal-weave = { git = "https://github.com/transkatgirl/universal-weave.git" }
